version: '3.4'

services:
  reportbro-server:
    image: reportbro-server
    environment:
      - BACKEND_MODE=db
      - DB_URL=mysql+aiomysql://root:root@localhost:3306/reportbro
    depends_on:
      - minio
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reportbro
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
