version: '3.4'
x-reportbro-common:
  &reportbro-common
  environment:
    &reportbro-common-env
    SHOW_DOC: ${SHOW_DOC:-true}
    # IS_DEBUG: ${IS_DEBUG:-true}

    MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
    MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
    MINIO_SITE_NAME: ${MINIO_SITE_NAME:-reportbro-s3}
    MINIO_SITE_REGION: ${MINIO_SECRET_KEY:-us-west-1}

services:
  reportbro-server:
    image: reportbro-server
    environment:
      - BACKEND_MODE=db
      - DB_URL=mysql+aiomysql://root:root@localhost:3306/reportbro
    depends_on:
      - minio
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reportbro
      # MYSQL_USER: your_username
      # MYSQL_PASSWORD: your_password
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

volumes:
  minio-data:
