name: 'sync Mirror to gitlab'
on: [push, delete]
jobs:
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false
      - name: 'Allow incomplete LFS push'
        run: git config lfs.allowincompletepush false
      - name: 'Mirror to gitlab'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            https://kaifeng.wu:AKSpEowKBCsbf82dNyFN@gitlab.a4apple.cn/react/reportbro-designer-api.git
      
